apiVersion: apps/v1
kind: Deployment
metadata:
  name: uc-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: uc-app
  template:
    metadata:
      labels:
        app: uc-app
    spec:
      containers:
        - name: nginx-container
          image: codemylove/uc-bazar:1.2
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
      restartPolicy: Always
      