apiVersion: v1
kind: Pod
metadata:
  name: uc-pod
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      imagePullPolicy: IfNotPresent
      ports:
        - name: http-port
          containerPort: 8081
          protocol: TCP
  restartPolicy: Always
  