apiVersion: v1
kind: Service
metadata:
  name: uc-service
spec:
  selector:
    app: uc-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30008
  type: NodePort
